export const FETCH_TIPOS_TRABAJO = 'FETCH_TIPOS_TRABAJO';
export const FETCH_TRABAJOS_ERROR = 'FETCH_TRABAJOS_ERROR';
export const FETCH_TIPOS_AUTORIZACION = 'FETCH_TIPOS_AUTORIZACION';
export const FETCH_FASES_TRABAJOS = 'FETCH_FASES_TRABAJOS';
export const CAMBIO_CONTENEDOR_CENTRAL = 'CAMBIO_CONTENEDOR_CENTRAL';
export const CAMBIO_CONTENEDOR_CENTRAL_RESET = 'CAMBIO_CONTENEDOR_CENTRAL_RESET';
