export const FETCH_EXPEDIENTES_INIT = 'FETCH_EXPEDIENTES_INIT';
export const FETCH_EXPEDIENTES_SUCCESS = 'FETCH_EXPEDIENTES_SUCCESS';
export const FETCH_EXPEDIENTES_ERROR = 'FETCH_EXPEDIENTES_ERROR';
export const FETCH_UBICACION_SUCCESS = 'FETCH_UBICACION_SUCCESS';
export const FETCH_EXPEDIENTE_SUCCESS = 'FETCH_EXPEDIENTE_SUCCESS';
export const FETCH_SAVE_ADRESS_TO_STORE = 'FETCH_SAVE_ADRESS_TO_STORE';
export const FETCH_EXPEDIENTSAVE_TO_STORE = 'FETCH_EXPEDIENTSAVE_TO_STORE';
export const FETCH_EXPEDIENTE_SUCCESS_EXP = 'FETCH_EXPEDIENTE_SUCCESS_EXP';
export const FETCH_SAVE_AGENTES_DATA = 'FETCH_SAVE_AGENTES_DATA';
export const FETCH_SAVE_TRABAJO_TO_STORE = 'FETCH_SAVE_TRABAJO_TO_STORE';
export const FETCH_DATAFORTREETRABAJO_SUCCESS = 'FETCH_DATAFORTREETRABAJO_SUCCESS';
export const SET_EXPEDIENTE_SELECTED = 'SET_EXPEDIENTE_SELECTED';
export const SET_EXPEDIENTE_SELECTED_DATOS = 'SET_EXPEDIENTE_SELECTED_DATOS';





