export const  traduccionGrid = {
    
        page: "pagina",
        more: "daMore",
        to: "daTo",
        of: "daOf",
        next: "next",
        last: "daLasten",
        first: "daFirsten",
        previous: "daPreviousen",
        loadingOoo: "daLoading...",
        selectAll: "daSelect Allen",
        searchOoo: "daSearch...",
        blanks: "daBlanc",
        filterOoo: "daFilter...",
        applyFilter: "daApplyFilter...",
        equals: "Igual",
        notEqual: "Distinto de",
        lessThanOrEqual: "daLessThanOrEqual",
        greaterThanOrEqual: "daGreaterThanOrEqual",
        inRange: "daInRange",
        lessThan: "daLessThan",
        greaterThan: "daGreaterThan",
        contains: "Contiene",
        startsWith: "daStarts dawith",
        endsWith: "acaba en",
        group: "laGroup",
        columns: "laColumns",
        rowGroupColumns: "laPivot Cols",
        rowGroupColumnsEmptyMessage: "la please drag cols to group",
        valueColumns: "laValue Cols",
        pivotMode: "laPivot-Mode",
        groups: "laGroups",
        values: "laValues",
        pivots: "laPivots",
        valueColumnsEmptyMessage: "la drag cols to aggregate",
        pivotColumnsEmptyMessage: "la drag here to pivot",
        noRowsToShow: "la no rows",
        pinColumn: "laPin Column",
        valueAggregation: "laValue Agg",
        autosizeThiscolumn: "laAutosize Diz",
        autosizeAllColumns: "laAutsoie em All",
        groupBy: "laGroup by",
        ungroupBy: "laUnGroup by",
        resetColumns: "laReset Those Cols",
        expandAll: "laOpen-em-up",
        collapseAll: "laClose-em-up",
        toolPanel: "laTool Panelo",
        export: "laExporto",
        csvExport: "la CSV Exportp",
        excelExport: "la Excel Exporto",
        pinLeft: "laPin <<",
        pinRight: "laPin >>",
        noPin: "laDontPin <>",
        sum: "laSum",
        min: "laMin",
        max: "laMax",
        first: "laFirst",
        last: "laLast",
        none: "laNone",
        count: "laCount",
        average: "laAverage",
        copy: "laCopy",
        ctrlC: "ctrl n C",
        paste: "laPaste",
        ctrlV: "ctrl n C"
    
}